### ISSUE TITLE
Overriding nested params from env ?

### ISSUE THREAD

**Issue by c0ze** [guidomb/app_configuration#3]
suppose you have a .config.yml like :

```
db:
  driver: "postgres"
  user: "coze"
  host: "localhost"
```

config.db becomes a hash. Is it possible to override db vars via ENV variables ? (ir something like `DB_NAME` etc ?)
